language: python
python:
  - "2.7"
env:
  - DJANGO=1.8
install:
  - pip install -r requirement/requirement.txt
before_script:
  - python manage.py syncdb –migrate –noinput
  - sh bin/init-secretkey.sh
script:
  - python manage.py test
