language: python
python:
  - "2.7"
env:
  - DJANGO=1.8
install:
  - pip install -r requirement/requirement.txt
before_script:
  - sh bin/init-secretkey.sh > tttt/settings/production.py
  - django-admin.py --version
  - python manage.py migrate –noinput
script:
  - python manage.py test apps.core.tests.SimpleTest